# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
