# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20160630_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2016, 6, 30, 21, 23, 21, 889185, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
