# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32)),
                ('mana_cost', models.SmallIntegerField(default=0)),
                ('damage', models.SmallIntegerField(default=0)),
                ('mana_damage', models.SmallIntegerField(default=0)),
                ('element', models.CharField(choices=[('fire', 'fire'), ('air', 'air'), ('earth', 'earth'), ('water', 'water')], max_length=8)),
            ],
        ),
    ]
