# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New deck', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeckElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Deck')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='spells.DeckElement', to='spells.Spell'),
        ),
        migrations.AlterUniqueTogether(
            name='deckelement',
            unique_together=set([('spell', 'deck')]),
        ),
    ]
