# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20160723_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='cards',
            new_name='elements',
        ),
    ]
