# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_auto_20160723_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='elements',
        ),
        migrations.AlterField(
            model_name='deckelement',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='spells.Deck'),
        ),
    ]
