# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_auto_20160723_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeckElement',
            new_name='DeckSpell',
        ),
        migrations.RenameField(
            model_name='deckspell',
            old_name='number',
            new_name='quantity',
        ),
    ]
