# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20160723_1602'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('in_hand', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='magestate',
            name='can_cast',
        ),
        migrations.RemoveField(
            model_name='magestate',
            name='can_move',
        ),
        migrations.RemoveField(
            model_name='magestate',
            name='discarded_spells',
        ),
        migrations.RemoveField(
            model_name='magestate',
            name='spells_in_hand',
        ),
        migrations.AddField(
            model_name='magestate',
            name='has_casted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magestate',
            name='has_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='mage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MageState'),
        ),
        migrations.AddField(
            model_name='card',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='spells.Spell'),
        ),
    ]
