# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160723_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magestate',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mages', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='magestate',
            name='location_x',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='magestate',
            name='location_y',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='magestate',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'team 1'), (2, 'team 2')], null=True),
        ),
    ]
