# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160724_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MageState',
            new_name='MageInGame',
        ),
    ]
